package com.pruebaMarshall.marshall.Servicio.Validaciones;

import org.springframework.stereotype.Service;

@Service
public class MONEDA {
    private static final String AED = "AED"; // Dirham de EAU
    private static final String AFN = "AFN"; // Afghani
    private static final String ALL = "ALL"; // Lek
    private static final String AMD = "AMD"; // Dram armenio
    private static final String ANG = "ANG"; // Florín antillano neerlandés
    private static final String AOA = "AOA"; // Kwanza
    private static final String ARS = "ARS"; // Peso Argentino
    private static final String AUD = "AUD"; // Dólar Australiano
    private static final String AWG = "AWG"; // Aruba Florin
    private static final String AZN = "AZN"; // Azerbaijanian Manat
    private static final String BAM = "BAM"; // Convertibles marca
    private static final String BBD = "BBD"; // Dólar de Barbados
    private static final String BDT = "BDT"; // Taka
    private static final String BGN = "BGN"; // Lev búlgaro
    private static final String BHD = "BHD"; // Dinar de Bahrein
    private static final String BIF = "BIF"; // Burundi Franc
    private static final String BMD = "BMD"; // Dólar de Bermudas
    private static final String BND = "BND"; // Dólar de Brunei
    private static final String BOB = "BOB"; // Boliviano
    private static final String BOV = "BOV"; // Mvdol
    private static final String BRL = "BRL"; // Real brasileño
    private static final String BSD = "BSD"; // Dólar de las Bahamas
    private static final String BTN = "BTN"; // Ngultrum
    private static final String BWP = "BWP"; // Pula
    private static final String BYR = "BYR"; // Rublo bielorruso
    private static final String BZD = "BZD"; // Dólar de Belice
    private static final String CAD = "CAD"; // Dólar Canadiense
    private static final String CDF = "CDF"; // Franco congoleño
    private static final String CHE = "CHE"; // WIR Euro
    private static final String CHF = "CHF"; // Franco Suizo
    private static final String CHW = "CHW"; // Franc WIR
    private static final String CLF = "CLF"; // Unidad de Fomento
    private static final String CLP = "CLP"; // Peso chileno
    private static final String CNH = "CNH"; // Yuan extracontinental (China )
    private static final String CNY = "CNY"; // Yuan Renminbi
    private static final String COP = "COP"; // Peso Colombiano
    private static final String COU = "COU"; // Unidad de Valor real
    private static final String CRC = "CRC"; // Colón costarricense
    private static final String CUC = "CUC"; // Peso Convertible
    private static final String CUP = "CUP"; // Peso Cubano
    private static final String CVE = "CVE"; // Cabo Verde Escudo
    private static final String CZK = "CZK"; // Corona checa
    private static final String DJF = "DJF"; // Franco de Djibouti
    private static final String DKK = "DKK"; // Corona danesa
    private static final String DOP = "DOP"; // Peso Dominicano
    private static final String DZD = "DZD"; // Dinar argelino
    private static final String EGP = "EGP"; // Libra egipcia
    private static final String ERN = "ERN"; // Nakfa
    private static final String ESD = "ESD"; // Dólar de Ecuador
    private static final String ETB = "ETB"; // Birr etíope
    private static final String EUR = "EUR"; // Euro
    private static final String FJD = "FJD"; // Dólar de Fiji
    private static final String FKP = "FKP"; // Libra malvinense
    private static final String GBP = "GBP"; // Libra Esterlina
    private static final String GEL = "GEL"; // Lari
    private static final String GHS = "GHS"; // Cedi de Ghana
    private static final String GIP = "GIP"; // Libra de Gibraltar
    private static final String GMD = "GMD"; // Dalasi
    private static final String GNF = "GNF"; // Franco guineano
    private static final String GTQ = "GTQ"; // Quetzal
    private static final String GYD = "GYD"; // Dólar guyanés
    private static final String HKD = "HKD"; // Dólar De Hong Kong
    private static final String HNL = "HNL"; // Lempira
    private static final String HRK = "HRK";
private static final String HTG = "HTG";
private static final String HUF = "HUF";
private static final String IDR = "IDR";
private static final String ILS = "ILS";
private static final String INR = "INR";
private static final String IQD = "IQD";
private static final String IRR = "IRR";
private static final String ISK = "ISK";
private static final String JMD = "JMD";
private static final String JOD = "JOD";
private static final String JPY = "JPY";
private static final String KES = "KES";
private static final String KGS = "KGS";
private static final String KHR = "KHR";
private static final String KMF = "KMF";
private static final String KPW = "KPW";
private static final String KRW = "KRW";
private static final String KWD = "KWD";
private static final String KYD = "KYD";
private static final String KZT = "KZT";
private static final String LAK = "LAK";
private static final String LBP = "LBP";
private static final String LKR = "LKR";
private static final String LRD = "LRD";
private static final String LSL = "LSL";
private static final String LYD = "LYD";
private static final String MAD = "MAD";
private static final String MDL = "MDL";
private static final String MGA = "MGA";
private static final String MKD = "MKD";
private static final String MMK = "MMK";
private static final String MNT = "MNT";
private static final String MOP = "MOP";
private static final String MRO = "MRO";
private static final String MUR = "MUR";
private static final String MVR = "MVR";
private static final String MWK = "MWK";
private static final String MXN = "MXN";
private static final String MXV = "MXV";
private static final String MYR = "MYR";
private static final String MZN = "MZN";
private static final String NAD = "NAD";
private static final String NGN = "NGN";
private static final String NIC = "NIC";
private static final String NIO = "NIO";
private static final String NOK = "NOK";
private static final String NPR = "NPR";
private static final String NZD = "NZD";
private static final String OMR = "OMR";
private static final String PAB = "PAB";
private static final String PEN = "PEN";
private static final String PGK = "PGK";
private static final String PHP = "PHP";
private static final String PKR = "PKR";
private static final String PLN = "PLN";
private static final String PYG = "PYG";
private static final String QAR = "QAR";
private static final String RON = "RON";
private static final String RSD = "RSD";
private static final String RUB = "RUB";
private static final String RWF = "RWF";
private static final String SAR = "SAR";
private static final String SBD = "SBD";
private static final String SCR = "SCR";
private static final String SDG = "SDG";
private static final String SEK = "SEK";
private static final String SGD = "SGD";
private static final String SHP = "SHP";
private static final String SLL = "SLL";
private static final String SOS = "SOS";
private static final String SRD = "SRD";
private static final String SSP = "SSP";
private static final String STD = "STD";
private static final String SVC = "SVC";
private static final String SYP = "SYP";
private static final String SZL = "SZL";
private static final String THB = "THB";
private static final String TJS = "TJS";
private static final String TMT = "TMT";
private static final String TND = "TND";
private static final String TOP = "TOP";
private static final String TRY = "TRY";
private static final String TTD = "TTD";
private static final String TWD = "TWD";
private static final String TZS = "TZS";
private static final String UAH = "UAH";
private static final String UGX = "UGX";
private static final String USD = "USD";
private static final String USN = "USN";
private static final String UYI = "UYI";
private static final String UYP = "UYP";
private static final String UYU = "UYU";
private static final String UZS = "UZS";
private static final String VEF = "VEF";
private static final String VES = "VES";
private static final String VND = "VND";
private static final String VUV = "VUV";
private static final String WST = "WST";
private static final String XAF = "XAF";
private static final String XAG = "XAG";
private static final String XAU = "XAU";
private static final String XBA = "XBA";
private static final String XBB = "XBB";
private static final String XBC = "XBC";
private static final String XBD = "XBD";
private static final String XCD = "XCD";
private static final String XDR = "XDR";
private static final String XOF = "XOF";
private static final String XPD = "XPD";
private static final String XPF = "XPF";
private static final String XPT = "XPT";
private static final String XSU = "XSU";
private static final String XTS = "XTS";
private static final String XUA = "XUA";
private static final String XXX = "XXX";
private static final String YER = "YER";
private static final String ZAR = "ZAR";
private static final String ZMW = "ZMW";
private static final String ZWL = "ZWL";


}
