package com.pruebaMarshall.marshall.Servicio.Validaciones;

import org.springframework.stereotype.Service;

@Service
public class MONEDA {
    private static final String AED = "2"; // Dirham de EAU
    private static final String AFN = "2"; // Afghani
    private static final String ALL = "2"; // Lek
    private static final String AMD = "2"; // Dram armenio
    private static final String ANG = "2"; // Florín antillano neerlandés
    private static final String AOA = "2"; // Kwanza
    private static final String ARS = "2"; // Peso Argentino
    private static final String AUD = "2"; // Dólar Australiano
    private static final String AWG = "2"; // Aruba Florin
    private static final String AZN = "2"; // Azerbaijanian Manat
    private static final String BAM = "2"; // Convertibles marca
    private static final String BBD = "2"; // Dólar de Barbados
    private static final String BDT = "2"; // Taka
    private static final String BGN = "2"; // Lev búlgaro
    private static final String BHD = "3"; // Dinar de Bahrein
    private static final String BIF = "0"; // Burundi Franc
    private static final String BMD = "2"; // Dólar de Bermudas
    private static final String BND = "2"; // Dólar de Brunei
    private static final String BOB = "2"; // Boliviano
    private static final String BOV = "2"; // Mvdol
    private static final String BRL = "2"; // Real brasileño
    private static final String BSD = "2"; // Dólar de las Bahamas
    private static final String BTN = "2"; // Ngultrum
    private static final String BWP = "2"; // Pula
    private static final String BYR = "0"; // Rublo bielorruso
    private static final String BZD = "2"; // Dólar de Belice
    private static final String CAD = "2"; // Dólar Canadiense
    private static final String CDF = "2"; // Franco congoleño
    private static final String CHE = "2"; // WIR Euro
    private static final String CHF = "2"; // Franco Suizo
    private static final String CHW = "2"; // Franc WIR
    private static final String CLF = "4"; // Unidad de Fomento
    private static final String CLP = "0"; // Peso chileno
    private static final String CNH = "2"; // Yuan extracontinental (China )
    private static final String CNY = "2"; // Yuan Renminbi
    private static final String COP = "2"; // Peso Colombiano
    private static final String COU = "2"; // Unidad de Valor real
    private static final String CRC = "2"; // Colón costarricense
    private static final String CUC = "2"; // Peso Convertible
    private static final String CUP = "2"; // Peso Cubano
    private static final String CVE = "2"; // Cabo Verde Escudo
    private static final String CZK = "2"; // Corona checa
    private static final String DJF = "0"; // Franco de Djibouti
    private static final String DKK = "2"; // Corona danesa
    private static final String DOP = "2"; // Peso Dominicano
    private static final String DZD = "2"; // Dinar argelino
    private static final String EGP = "2"; // Libra egipcia
    private static final String ERN = "2"; // Nakfa
    private static final String ESD = "2"; // Dólar de Ecuador
    private static final String ETB = "2"; // Birr etíope
    private static final String EUR = "2"; // Euro
    private static final String FJD = "2"; // Dólar de Fiji
    private static final String FKP = "2"; // Libra malvinense
    private static final String GBP = "2"; // Libra Esterlina
    private static final String GEL = "2"; // Lari
    private static final String GHS = "2"; // Cedi de Ghana
    private static final String GIP = "2"; // Libra de Gibraltar
    private static final String GMD = "2"; // Dalasi
    private static final String GNF = "0"; // Franco guineano
    private static final String GTQ = "2"; // Quetzal
    private static final String GYD = "2"; // Dólar guyanés
    private static final String HKD = "2"; // Dólar De Hong Kong
    private static final String HNL = "2"; // Lempira
    private static final String HRK = "2";
private static final String HTG = "2";
private static final String HUF = "2";
private static final String IDR = "2";
private static final String ILS = "2";
private static final String INR = "2";
private static final String IQD = "3";
private static final String IRR = "2";
private static final String ISK = "0";
private static final String JMD = "2";
private static final String JOD = "3";
private static final String JPY = "0";
private static final String KES = "2";
private static final String KGS = "2";
private static final String KHR = "2";
private static final String KMF = "0";
private static final String KPW = "2";
private static final String KRW = "0";
private static final String KWD = "3";
private static final String KYD = "2";
private static final String KZT = "2";
private static final String LAK = "2";
private static final String LBP = "2";
private static final String LKR = "2";
private static final String LRD = "2";
private static final String LSL = "2";
private static final String LYD = "3";
private static final String MAD = "2";
private static final String MDL = "2";
private static final String MGA = "2";
private static final String MKD = "2";
private static final String MMK = "2";
private static final String MNT = "2";
private static final String MOP = "2";
private static final String MRO = "2";
private static final String MUR = "2";
private static final String MVR = "2";
private static final String MWK = "2";
private static final String MXN = "2";
private static final String MXV = "2";
private static final String MYR = "2";
private static final String MZN = "2";
private static final String NAD = "2";
private static final String NGN = "2";
private static final String NIC = "2";
private static final String NIO = "2";
private static final String NOK = "2";
private static final String NPR = "2";
private static final String NZD = "2";
private static final String OMR = "3";
private static final String PAB = "2";
private static final String PEN = "2";
private static final String PGK = "2";
private static final String PHP = "2";
private static final String PKR = "2";
private static final String PLN = "2";
private static final String PYG = "0";
private static final String QAR = "2";
private static final String RON = "2";
private static final String RSD = "2";
private static final String RUB = "2";
private static final String RWF = "0";
private static final String SAR = "2";
private static final String SBD = "2";
private static final String SCR = "2";
private static final String SDG = "2";
private static final String SEK = "2";
private static final String SGD = "2";
private static final String SHP = "2";
private static final String SLL = "2";
private static final String SOS = "2";
private static final String SRD = "2";
private static final String SSP = "2";
private static final String STD = "2";
private static final String SVC = "2";
private static final String SYP = "2";
private static final String SZL = "2";
private static final String THB = "2";
private static final String TJS = "2";
private static final String TMT = "2";
private static final String TND = "3";
private static final String TOP = "2";
private static final String TRY = "2";
private static final String TTD = "2";
private static final String TWD = "2";
private static final String TZS = "2";
private static final String UAH = "2";
private static final String UGX = "0";
private static final String USD = "2";
private static final String USN = "2";
private static final String UYI = "0";
private static final String UYP = "2";
private static final String UYU = "2";
private static final String UZS = "2";
private static final String VEF = "2";
private static final String VES = "2";
private static final String VND = "0";
private static final String VUV = "0";
private static final String WST = "2";
private static final String XAF = "0";
private static final String XAG = "0";
private static final String XAU = "0";
private static final String XBA = "0";
private static final String XBB = "0";
private static final String XBC = "0";
private static final String XBD = "0";
private static final String XCD = "2";
private static final String XDR = "0";
private static final String XOF = "0";
private static final String XPD = "0";
private static final String XPF = "0";
private static final String XPT = "0";
private static final String XSU = "0";
private static final String XTS = "0";
private static final String XUA = "0";
private static final String XXX = "0";
private static final String YER = "2";
private static final String ZAR = "2";
private static final String ZMW = "2";
private static final String ZWL = "2";


}
